### PR TITLE
Correct English language and add Part numbers

### PR DESCRIPTION
**Pull request by peterhauke**
Corrected some minor grammar errors.
Improved the style.
Removed some less common wording.
Simplified the style.
Added Part 1 to the title
Added part numbers to the links at the bottom -- the actual parts themselves are not numbered elsewhere, but if this proposal is accepted then I will number the other parts accordingly
I corrected  "uses a [function as a child]" but it could also be "uses [functions as children]". At this moment, I am not sure which is better in this context.

### CODE REVIEW

**Comment by rwieruch** [comment]
Hi @peterhauke I like most of the changes! I would keep the Part(s) out there though. It's correct that this initial tutorial is the first part, however, all the other tutorials can come in any order. So I'd not give them (and this blog post) any parts whatsoever. Also I see a `&ndash;` somewhere in there that may be not needed.

Thanks again!

**Comment by peterhauke** [comment]
I removed the Part(s), however, the other parts of the tutorial mention parts at the top of the page, for example: https://www.robinwieruch.de/react-table-fixed-column/

I would suggest that the list of links at the bottom of this page appears at the bottom of the other tutorials and the links at the top can be removed. 

Can the list of links at the bottom be automated?

I will ignore this for the time being when I correct the other tutorials.

**Comment by peterhauke** [comment]
Hi @rwieruch, I have removed the references I made to Part(s) in this article so I think you can accept it if you are happy with it now.

**Comment by rwieruch** [comment]
Perfect. Thank you so much @peterhauke 🚀

**Comment by rwieruch** [comment]
Hey @peterhauke ! Thanks for all what you have done in your PRs. FYI I am writing "The Road to JavaScript" which is 80% done. If you want to take a look over there, I'd be super happy. Usually I find several developers on Upwork who want to go through the book for proofreading and feedback as well. Just if you are interested: https://github.com/the-road-to-javascript/the-road-to-javascript 🚀

**Pull request merged**
