### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by UmungoBungo**
Minor grammar and spelling for this bonza article

### CODE REVIEW

**Comment by rwieruch** [comment]
Oh perfect! Thank you 🎉 👍

**Comment by rwieruch** [comment]
Is this ready to be merged @UmungoBungo ?

**Comment by UmungoBungo** [comment]
Ready now, there are some subjective changes towards the end, feel free to go your own way 👌

**Comment by rwieruch** [comment]
This is amazing! Thank you so much @UmungoBungo 🎉 🎉 ⭐

**Pull request merged**
