### PR TITLE
Replace render props with component props

### PR DESCRIPTION
**Pull request by abraj**
The explanation needs improvement because of a previous change which changed `component` prop to `render` prop in the Route components.

### CODE REVIEW

**Comment by abraj** [comment]
The corresponding change for the repo `the-road-to-react-with-firebase` already available in the [PR #9]([url](https://github.com/rwieruch/the-road-to-react-with-firebase/pull/9))

**Comment by abraj** [comment]
Renaming PR title from "Improve explanation for the use of render props" to  "Replace render props with component props"

**Comment by abraj** [comment]
Changes done as per discussion on [PR #52](https://github.com/rwieruch/blog_robinwieruch_content/pull/52).

**Comment by rwieruch** [comment]
Perfect @abraj

**Pull request merged**
